# Use an official Node Docker image as the base
FROM node:20.7.0

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./ /app