[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

# [[bin]]
# name = "null_char"
# path = "null_char.rs"

# [[bin]]
# name = "stdin"
# path = "stdin.rs"

[[bin]]
name = "read_file"
path = "read_file.rs"
