# Use an official php runtime as the base image
FROM php:8

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./ /app
